# Generated by Django 4.1 on 2024-09-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand of car')),
                ('model', models.CharField(max_length=200, verbose_name='Model of car')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_main_photo/', verbose_name="Car's main photo")),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creating')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('engine', models.CharField(max_length=30, verbose_name='Engine')),
                ('quantity', models.IntegerField(verbose_name='Quantity of cars')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Photos of cars')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Salon.cars')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
